# Copyright 2020 Walmart Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM docker.pkg.github.com/arsulegai/hgf2020/rust-installed:latest as builder

RUN mkdir -p /pc

COPY processor /pc

RUN mkdir -p /protos

COPY protos /protos

WORKDIR /pc

RUN cargo build

#=============================================================================    

FROM docker.pkg.github.com/arsulegai/hgf2020/rust-installed:latest

COPY --from=builder /pc/target/debug/produce-consume  /produce-consume
